### ISSUE TITLE
Precomputed ScanNet for all alphafold structures/PDB structure

### ISSUE THREAD

**Issue by andreassteffen** [jertubiana/ScanNet#1]
Hi,
very nice work indeed! Do you happen to have precomputed the ScanNet binding probabilities for all alphafold/PDB structures and is there perhaps a way to download all of them?
very many thanks, Andreas

**Comment by jertubiana** [comment]
Dear Andreas,
Thank you for your interest in ScanNet.
Unfortunately, we don't have precomputed values for all AlphaFold/PDB structures.
It is possible to run the network over a list of inputs. For instance,

python predict_bindingsites.py list_inputs.txt --noMSA 

Where list_inputs.txt is a simple text file such as:

1brs_A
2p6b_AB
...

The .txt extension is mandatory. All the results will be stored in the prediction folder.

If you need to run it over a few hundreds of structures, this should work fine. Hope this will help you.
Jérôme

**Comment by andreassteffen** [comment]
thank you!
