### ISSUE TITLE
Question regarding the pretrained model and model representation

### ISSUE THREAD

**Issue by Tizzzzy** [jertubiana/ScanNet#12]
Hi author!
Huge fan of your work. When I read the README, I didn't see the step of loading the pretrained model. I was wondering for command `python predict_bindingsites.py 1brs_A --noMSA`, the pretrained model will load automatically or not?
Also, is it possible to input a protein pdb file, then extract the latent representation of this protein from the model? If this is possible, can you please show me which line of code is the latent representation of a protein.
Thank you so much

**Comment by jertubiana** [comment]
Hi,
Thank you for your interest in your research and your warm words.

> On 9 Sep 2024, at 18:34, Tizzzzzzy ***@***.***> wrote:
> 
> 
> Hi author!
> Huge fan of your work. When I read the README, I didn't see the step of loading the pretrained model. I was wondering for command python predict_bindingsites.py 1brs_A --noMSA, the pretrained model will load automatically or not?
> 

Yes, it will load the pretrained model.

> Also, is it possible to input a protein pdb file, then extract the latent representation of this protein from the model? If this is possible, can you please show me which line of code is the latent representation of a protein.
> 

See the predict_features.py script, which outputs an embedding for each amino acid. To get a protein-level embeddings, you can average across amino acids.


Best,
Jerome

**Comment by Tizzzzy** [comment]
Hi Jerome, 
Just want to double check with you. In `predict_features.py`, there are two format: `numpy` and `dictionary`. 
When `output_format == 'numpy'`, the embedding for each amino acid is stored in `query_features`.
When `output_format == 'dictionary'`, the embedding for each amino acid is stored in `query_dictionary_features`.
Please correct me if I am wrong. Thank you

**Comment by jertubiana** [comment]
Correct

**Comment by Tizzzzy** [comment]
Hi Jerome,
I still have some questions:
1. Does `predict_features.py` also support one protein? I know in the original script, the code support multiple proteins, since there are two proteins in the `list_quries`, like this: `predict_features(['1a3x_A','1brs_A']...`. However, if I only put one protein in the code, it can still run. So I want to double check with you that if I only put one protein, does the embedding for each amino acid still correct? (Right now the embedding shape is (num_amino_acid, 96))
2. When I print out the embedding, some amino acid has embedding 0. Is it normal?

Thank you for your time

**Comment by jertubiana** [comment]
1. Sorry for the belated answer. Yes, it works (it will turn it into a list with one element inside the function).
2. Yes, it is normal. It is the effect of the ReLU activation. The features are still informative, because the 0's are dynamic and depend on the amino acid environment.
