### ISSUE TITLE
tensorflow-gpu version

### ISSUE THREAD

**Issue by wenyuhaokikika** [jertubiana/ScanNet#2]
Hi,
very nice work indeed! 
can you provide your tensorflow-gpu version? i encounter some problem when I try use ScanNet to run demo.
## install
```
git clone https://github.com/jertubiana/ScanNet.git
cd ScanNet
conda create -n py_scannet python=3.6.12
conda activate py_scannet
```
i delete row ```tensorflow==1.14.0``` in requirements.txt because i want use gpu.
then i install packages with ```pip install -r requirements.txt;pip install tensorflow-gpu```.
<details>
  <summary>
   version in my environment
  </summary>
<code>
<p> Package                 Version </p>    <p>----------------------- ----------- </p>    <p>absl-py                 0.15.0 </p>    <p>argon2-cffi             21.3.0 </p>    <p>argon2-cffi-bindings    21.2.0 </p>    <p>astunparse              1.6.3 </p>    <p>async-generator         1.10 </p>    <p>attrs                   22.1.0 </p>    <p>backcall                0.2.0 </p>    <p>biopython               1.78 </p>    <p>bleach                  4.1.0 </p>    <p>cached-property         1.5.2 </p>    <p>cachetools              4.2.4 </p>    <p>certifi                 2022.6.15 </p>    <p>cffi                    1.15.1 </p>    <p>charset-normalizer      2.0.12 </p>    <p>clang                   5.0 </p>    <p>cycler                  0.11.0 </p>    <p>dataclasses             0.8 </p>    <p>decorator               5.1.1 </p>    <p>defusedxml              0.7.1 </p>    <p>entrypoints             0.4 </p>    <p>flatbuffers             1.12 </p>    <p>gast                    0.4.0 </p>    <p>google-auth             1.35.0 </p>    <p>google-auth-oauthlib    0.4.6 </p>    <p>google-pasta            0.2.0 </p>    <p>grpcio                  1.47.0 </p>    <p>h5py                    3.1.0 </p>    <p>idna                    3.3 </p>    <p>importlib-metadata      4.8.3 </p>    <p>ipydatawidgets          4.3.1.post1 </p>    <p>ipykernel               5.5.6 </p>    <p>ipython                 7.16.3 </p>    <p>ipython-genutils        0.2.0 </p>    <p>ipywebrtc               0.5.0 </p>    <p>ipywidgets              7.5.1 </p>    <p>jedi                    0.17.2 </p>    <p>Jinja2                  3.0.3 </p>    <p>joblib                  1.1.0 </p>    <p>jsonschema              3.2.0 </p>    <p>jupyter-client          7.1.2 </p>    <p>jupyter-core            4.9.2 </p>    <p>jupyterlab-pygments     0.1.2 </p>    <p>keras                   2.6.0 </p>    <p>Keras-Applications      1.0.8 </p>    <p>Keras-Preprocessing     1.1.2 </p>    <p>kiwisolver              1.3.1 </p>    <p>llvmlite                0.35.0 </p>    <p>Markdown                3.3.7 </p>    <p>MarkupSafe              2.0.1 </p>    <p>matplotlib              3.3.3 </p>    <p>mistune                 0.8.4 </p>    <p>nbclient                0.5.9 </p>    <p>nbconvert               6.0.7 </p>    <p>nbformat                5.1.3 </p>    <p>nest-asyncio            1.5.5 </p>    <p>notebook                6.4.10 </p>    <p>numba                   0.52.0 </p>    <p>numpy                   1.19.5 </p>    <p>oauthlib                3.2.0 </p>    <p>opt-einsum              3.3.0 </p>    <p>packaging               21.3 </p>    <p>pandas                  1.1.5 </p>    <p>pandocfilters           1.5.0 </p>    <p>parso                   0.7.1 </p>    <p>pexpect                 4.8.0 </p>    <p>pickleshare             0.7.5 </p>    <p>Pillow                  8.4.0 </p>    <p>pip                     21.3.1 </p>    <p>prometheus-client       0.14.1 </p>    <p>prompt-toolkit          3.0.30 </p>    <p>protobuf                3.19.4 </p>    <p>ptyprocess              0.7.0 </p>    <p>pyasn1                  0.4.8 </p>    <p>pyasn1-modules          0.2.8 </p>    <p>pycparser               2.21 </p>    <p>Pygments                2.13.0 </p>    <p>pyparsing               3.0.9 </p>    <p>pyrsistent              0.18.0 </p>    <p>python-dateutil         2.8.2 </p>    <p>pythreejs               2.3.0 </p>    <p>pytz                    2022.2.1 </p>    <p>PyYAML                  6.0 </p>    <p>pyzmq                   23.2.1 </p>    <p>requests                2.27.1 </p>    <p>requests-oauthlib       1.3.1 </p>    <p>rsa                     4.9 </p>    <p>scikit-learn            0.24.2 </p>    <p>scipy                   1.5.4 </p>    <p>Send2Trash              1.8.0 </p>    <p>setuptools              58.0.4 </p>    <p>six                     1.15.0 </p>    <p>tensorboard             2.6.0 </p>    <p>tensorboard-data-server 0.6.1 </p>    <p>tensorboard-plugin-wit  1.8.1 </p>    <p>tensorflow-estimator    2.6.0 </p>    <p>tensorflow-gpu          2.6.2 </p>    <p>termcolor               1.1.0 </p>    <p>terminado               0.12.1 </p>    <p>testpath                0.6.0 </p>    <p>threadpoolctl           3.1.0 </p>    <p>tornado                 6.1 </p>    <p>traitlets               4.3.3 </p>    <p>traittypes              0.2.1 </p>    <p>typing-extensions       3.7.4.3 </p>    <p>urllib3                 1.26.12 </p>    <p>wcwidth                 0.2.5 </p>    <p>webencodings            0.5.1 </p>    <p>Werkzeug                2.0.3 </p>    <p>wheel                   0.37.1 </p>    <p>widgetsnbextension      3.5.2 </p>    <p>wrapt                   1.12.1 </p>    <p>zipp                    3.6.0 <p>
</code>
</details>

## run
then i run ```python predict_bindingsites.py P38398 --noMSA```, it raise exception
```
  File "predict_bindingsites.py", line 406, in predict_interface_residues
    model_obj = wrappers.load_model(model_folder + model, Lmax=Lmax)
  File "/data/wenyuhao/code/ScanNet/utilities/wrappers.py", line 80, in load_model
    model_builder, *model_args, **model_kwargs, backend=backend, **wrapper_builder_kwargs)
  File "/data/wenyuhao/code/ScanNet/utilities/wrappers.py", line 217, in __init__
    model_builder, *args, backend=backend, **kwargs)
  File "/data/wenyuhao/code/ScanNet/utilities/wrappers.py", line 95, in __init__
    self.model = self.model_builder(*self.args, **self.kwargs)
  File "/data/wenyuhao/code/ScanNet/network/scannet.py", line 351, in ScanNet
    embedded_attributes_aa = attribute_embedding(masked_attributes_aa,nembedding_aa,activation,name='embedded_attributes_aa')
  File "/data/wenyuhao/code/ScanNet/network/scannet.py", line 90, in attribute_embedding
    name=name)
  File "/data/wenyuhao/code/ScanNet/network/scannet.py", line 69, in addNonLinearity
    epsilon=1e-3, axis=-1, center=center, scale=scale, name=name + '_normalization')(input_layer) # Custom batch norm layer that takes into account the mask.
  File "/data/wenyuhao/anaconda3/envs/py_scannet/lib/python3.6/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "/data/wenyuhao/anaconda3/envs/py_scannet/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/data/wenyuhao/anaconda3/envs/py_scannet/lib/python3.6/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/data/wenyuhao/anaconda3/envs/py_scannet/lib/python3.6/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/data/wenyuhao/anaconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /data/wenyuhao/code/ScanNet/network/embeddings.py:464 call  *
        del reduction_axes[self.axis]

    TypeError: list indices must be integers or slices, not ListWrapper
```
because of value axis of the object  MaskedBatchNormalization is ListWrapper in  /network/embeddings.py:464 .
maybe version of tensorflow-gpu is not matched.
it really make confused , run in centos7. Looking forward to.

**Comment by jertubiana** [comment]
Hi,
Thanks for your interest in our research! Sorry for the issue, the right tensorflow-gpu version is tensorflow-gpu==1.14.
Please let me know if that works for you.
Best regards,
Jérôme

**Comment by wenyuhaokikika** [comment]
Thank you! it works for me after installing tensorflow-gpu==1.14!!! very nice work.

And i will get some numba warinings,such as
```
/data/wenyuhao/anaconda3/envs/py_scannet/lib/python3.6/site-packages/numba/typed/typedlist.py:66: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'item' of function 'impl_append.<locals>.impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "../../anaconda3/envs/py_scannet/lib/python3.6/site-packages/numba/typed/listobject.py", line 597:

    def impl(l, item):
    ^

  l.append(item)
```
i think it also because of version of numba mismatch,can i see your full requenirment.txt in your environment? 
Thank you.
