### ISSUE TITLE
amino acid frame triplet side chain 

### ISSUE THREAD

**Issue by biochunan** [jertubiana/ScanNet#4]
Hello, thanks for open sourcing your project. 

I was wondering if I train ScanNet from scratch, should I modify line 170 to use Nitrogen atom of the current amino acid `atom_coordinate` instead of the previous aimo acid i.e. `atom_coordinates[l-1]`. I noticed in your comment that it was due to a previou issue. So just to confirm if I retrain the network, my understanding is I should replace line 169-175 line 182-188, is that correct? 

https://github.com/jertubiana/ScanNet/blob/77d851037ef564b8d10aa0e23f063eb1c9243ea6/preprocessing/protein_frames.py#L166-L188

**Comment by jertubiana** [comment]
Hi,
Thanks for your interest in our research.
Regarding protein_frames.py, please leave as it is, the change was already made.
However, if you retrain, you can comment l427 of file preprocessing/protein_chemistry.py and uncomment l428.
This is a bug regarding histidine parsing that I only noticed recently.
Best regards,
Jérôme

**Comment by biochunan** [comment]
Thansk for your reply! Though I am still confused about line 169-171 in protein_frames.py 

For examle, a Glycine (residue index `l`), as in line 169-171 you are calculating its virtual side-chain CoM using the glycine's C and Cα atom coordinates and the Nitrogen atom of its preceding residue (`l-1`) if I understand correctly. In your paper, the side chain CoM was defined using `Cα`, `C`, `N` atom vector coordinates of the residue. So, why using nitrogen from preceding residue `atom_coordinates[l-1][atom_ids[l-1].index(17)]` rather than the glycine its own nitrogen atom e.g. `atom_coordinate[atom.index(17)]`?

**Comment by jertubiana** [comment]
Hi, sorry for the belated reply and the confusion.
After double checking the situation, you are correct. 
You should indeed comment out 169-171). I thought I had already made the correction but had actually not.
Thanks for pointing out the issue, and best of luck for your future research.
Best,
Jérôme
