### ISSUE TITLE
Detect active sites of enzymes that binding and catalyzing substrate?

### ISSUE THREAD

**Issue by BinhongLiu** [jertubiana/ScanNet#5]
Hi,
    Really nice tool! Could ScanNet be used to detect active sites of an enzyme that bind and catalyze substrates? Thanks!

**Comment by jertubiana** [comment]
Hi Hongbin,
Thank you for your interest in our research. In principle, yes, ScanNet is suitable to detect active sites. Extended Data Figure 7d shows that the learnt amino acid representation captures the convexity of the molecular surface, which is a key property of active sites. You would need to fine-tune the model on a dedicated training set.
Best,
Jérôme

**Comment by BinhongLiu** [comment]
Thanks for your prompt reply! Yes, I agree that fine-tuning the model on a dedicated training set will be better.  Since preparing the dedicated training set may take me some time. I'd like to use the current model directly, though I'm not sure how much the predictions for the active site will be affected using the current model. Thanks again.
