### ISSUE TITLE
Problems with retraining

### ISSUE THREAD

**Issue by c-y-1** [jertubiana/ScanNet#6]
Hello, when I run "python train.py" to retrain, this prompt appears. How can I solve it? 

Failed to process example 2as0_0-A (3/3194), Error: [Errno 2] No such file or directory: 'MSA/MSA_2as0_0_A_query.fasta'

It would be my pleasure if you could answer it

**Comment by jertubiana** [comment]
Hi,
Thank you for your interest in your research.
The error means that you are trying to retrain the model with multiple sequence alignment (MSA) information, but have not installed HH-blits to generate the MSAs
Please set the use_evolutionary flag to False (l80), and it should work.
Best,
Jerome
