### ISSUE TITLE
[Question] Running ScanNet in Docker on a MacBook with AMD chipset

### ISSUE THREAD

**Issue by agdiaz** [jertubiana/ScanNet#8]
Dear Jérôme, 
How are you? I hope you are doing well.

## Abstract

I would like to try your software tool directly as a Docker container on my laptop that has an Apple Silico chipset (ARM architecture instead of x64). However, when I try to run it, I receive an error message:

```bash
Using TensorFlow backend.
Illegal instruction
```

## Context information

My current environment is:

- Laptop: Apple M2 Pro, OS version 14.2.1 (23C71). 
- Docker version: Docker version 24.0.7, build afdd53b
- Test command: `python predict_bindingsites.py 1brs_A --noMSA`

Settings for Docker engine:
<img width="1053" alt="image" src="https://github.com/jertubiana/ScanNet/assets/1646576/cc9a3e99-688e-4f68-b5c5-60a9eb9128f9">

I have tested the image by doing:

```console
$ DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run --rm -it -v $PWD/data:/data jertubiana/scannet /bin/bash
root@2d0f05562a11:/ScanNet# python predict_bindingsites.py 1brs_A --noMSA
Using TensorFlow backend.
Illegal instruction
```

I have also cloned the repository and created another Dockerfile to install the dependencies (from the requirements.txt file) with the same results. 

I have also found a comment on StackOverflow saying that downgrading the `tensorflow` version may fix it. However, it raised different errors due to invalid compatibility between the code and the libraries' versions. 

## Question(s)

Do you have a workaround to fix it or another docker image built for ARM architectures? 
Thank you so much in advance for your feedback and guidance.

Best regards from Brussels,
Adrián

**Comment by jertubiana** [comment]
Hi Adrian, sorry for the delay, did you manage to fix the problem?
One option could be to upgrade to Tensorflow2. Please email me at ***@***.*** and I’ll send source code (still in dev.)
Best,
Jerome

**Comment by agdiaz** [comment]
Hello Jérôme,

Thank you for your answer. Indeed, the staff of the HPC at my university recommended to use TensorFlow2 in case I wanted to install it on their infrastructure, otherwise it can't be officially installed as a HPC module.
I will contact you to see how I could help to test the dev version with TensorFlow2. 

Kind regards,
Adrián
